{% set name = "xrf-tomo" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xrf-tomo-{{ version }}.tar.gz
  sha256: 7848c54c802032ced122423bdfd8cfc03838a4959fccb4284dadf48737d7af42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - h5py
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy
    - tomopy
    - pystackreg
    - pyxrf >=1.0.16

test:
  requires:
    - python {{ python_min }}
  imports:
    - xrf_tomo

about:
  home: https://github.com/NSLS-II-SRX/xrf-tomo
  summary: XRF Tomography Reconstruction
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://github.com/NSLS-II-SRX/xrf-tomo
  dev_url: https://github.com/NSLS-II-SRX/xrf-tomo

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
    - XYangXRay
